/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "project-S&B_Card_Signatures-lvlD4XwykxLTf05CbjqI0-chCWa8Zsvv",
  "version": "2020-11-20"
}

export default ebconfig;